# This pipeline shows how to:
# - Provision an Azure VM and register the VM in an Azure Pipelines environment.
# - Run a task like InstallNetCoreRuntimeAndHosting on the provisioned VM.
# - Remove the used Azure Pipelines environment and provisioned Azure resource group.
#
# The following variables need to be provided to the pipeline:
# - token           : a Personal Access Token with the scopes 'Environment (Read & manage)' and 'Tokens (Read & manage)'.
# - adminPassword   : a password for the admin user of the virtual machine.
#
# This pipeline also expects an Azure (Resource Manager) service connection in Azure DevOps with the name 'Azure Visual Studio Enterprise'.


trigger: none
pr: none

pool:
  name: easec-pool
  
variables:
  sourceResourceGroupName: "snapshottest-rg"
  resourceGroupName: "snapshot-rg"
  snapshotName: "easec-vm_OsDisk_1_snap"
  snapshotNameData: "easec-vm_DataDisk_0_snap"
  osDiskName: "easec-vm_OsDisk_1_man"
  dataDiskName: "easec-vm_DataDisk_1_man"
  diskSizeOs: 128
  diskSizeData: 1024
  storageType: "Premium_LRS"
  osType: "windows"
  virtualMachineName: "easec-vm"

stages:
- stage: Provision
  jobs:
  - job:
    steps:
     - task: AzureCLI@2
       inputs:
         azureSubscription: 'MyAzureServiceConnection'
         scriptType: pscore
         scriptLocation: inlineScript
         inlineScript: |
          $snapshotSourceId=$(az snapshot show --name "$(snapshotName)" --resource-group "$(sourceResourceGroupName)" --query "id" -o tsv
          Write-Host "Source Snapshot ID: $snapshotSourceId"